import "../../styles/globals.css"; 

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>User Management App</title>
        <meta
          name="description"
          content="Next.js application with TypeScript and Tailwind CSS for user management."
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body
        suppressHydrationWarning={true}
        className="flex flex-col min-h-screen bg-gray-100 text-gray-900"
      >
        {children}
      </body>
    </html>
  );
}

// import React from "react";
// import "../styles/globals.css";

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <head>
//         <meta charSet="utf-8" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <title>Your App Name</title>
//       </head>
//       <body
//         key="body"
//         className="flex flex-col min-h-screen bg-background text-foreground"
//       >
//         <header className="bg-gray-100 p-4">
//           {/* Add your Navbar component here */}
//         </header>
//         <main className="flex-grow container mx-auto px-4 py-8">
//           {children}
//         </main>
//         <footer className="bg-gray-100 p-4 mt-auto">
//           {/* Add your Footer component here */}
//         </footer>
//       </body>
//     </html>
//   );
// }

// import type { Metadata } from "next";
// import localFont from "next/font/local";
// import "./globals.css";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
